.TH rapd 1  "March 20, 2022" "version 0.1" "USER COMMANDS"
.SH NAME
rapc - Rust Audio Player Client
.SH DESCRIPTION
Rapc is a basic command-line based client for RAPD

.SH SYNOPSIS
.INDENT 0.0
.INDENT 3.5
rapc [options] <command> [<arguments>]

.SH OPTIONS
.INDENT 0.0
.TP
.B \-h, \-\-help
Print help for a command, or for rapc

.SH COMMANDS
.INDENT 0.0
.TP
.B \fBplayer_stop\fB
Halts the player 
.TP
.B \fBplayer_file\fB
Print the current playing file, prints "empty" if nothing
.TP
.B \fBplayer_state\fB
Print the state of the rapd server/player
.TP
.B \fBplayer_pause\fB
Pause the player
.TP
.B \fBplayer_unpause\fB
Unpause the player
.TP
.B \fBshutdown_server\fB
Shutsdown the RAPD server
.TP
.B \fBplay [file]\fB
Plays a audio file from disk, will not play
if the server is already playing an audio file.
.TP
.B \fBdb_print\fB
Print a list of the contents in the music database
.TP
.B \fBdb_rebuild\fB
Rebuild the music database
.TP
.B \fBdb_select\fB
Select an item to play from the music database
.TP
.B \fBhelp [command]\fB
Print a help message for a command
.TP
.B \fBhook_add_player_pause [cmd]\fB
Add a hook that fires on player pause
.TP
.B \fBhook_add_player_start [cmd]\fB
Add a hook that fires on player start
.TP
.B \fBhook_add_player_unpause [cmd]\fB
Add a hook that fires on player unpause
.TP
.B \fBhook_add_server_shutdown [cmd]\fB
Add a hook that fires on server shutdown
.TP
.B \fBmetadata_get_title [file]\fB
Get the metadata title for a file
.TP
.B \fBmetadata_set_title [file]\fB
Set the metadata title for a file
.UNIDENT

.SH BUGS
.INDENT 0.0
Report all bugs at https://github.com/Interfiber/rapd
.UNIDENT

.SH AUTHOR
Interfiber <webmaster@interfiber.dev>
.SH SEE ALSO
rapd(1)
